name: .NET Core

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install dependencies
      run: dotnet restore BulletSharp/BulletSharp.DotNetCore.csproj
    - name: Build
      run: dotnet build --configuration Release --no-restore BulletSharp/BulletSharp.DotNetCore.csproj
    - name: Test
      run: dotnet test --no-restore --verbosity normal BulletSharp/BulletSharp.DotNetCore.csproj
